accelerometer_noise_density: 0.0042   
accelerometer_random_walk: 1.5e-04    
gyroscope_noise_density: 0.00052      
gyroscope_random_walk: 1.2e-05        

rostopic: '/camera/camera/imu' 
update_rate: 400 



